/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package com.example.androidthings.imageclassifier;

public final class R {
  public static final class color {
    public static final int control_background=0x7f010000;
  }
  public static final class id {
    public static final int container=0x7f020000;
    public static final int imageView=0x7f020001;
    public static final int result1=0x7f020002;
    public static final int result2=0x7f020003;
    public static final int result3=0x7f020004;
    public static final int results=0x7f020005;
  }
  public static final class layout {
    public static final int activity_camera=0x7f030000;
  }
  public static final class string {
    public static final int app_name=0x7f040000;
    public static final int camera_error=0x7f040001;
    public static final int description_info=0x7f040002;
    public static final int help_message=0x7f040003;
    public static final int request_permission=0x7f040004;
  }
}